api: api14
api14: api14
bhllat27: bhllat
bhllatnad27: bhllat
bhllon27: bhllon
bhllong: bhllon
bhllonnad27: bhllon
bottomholelat: bhllat
bottomholelong: bhllon
companyname: operator
end: fracenddate
fraccompany: operator
scheduledfracenddate: fracenddate
scheduledfracstartdate: fracstartdate
shllat27: shllat
shllatnad27: shllat
shllon27: shllon
shllong: shllon
shllong2: shllon
shllongnad27: shllon
shllonnad27: shllon
start: fracstartdate
surfacelat: shllat
surfacelong: shllon
tvdattd: tvd
