_known_files:
  /repositories/permian-frac-exchange/data/Apache Frac Schedule.xlsx: '2019-08-23T18:14:59.588020'
  /repositories/permian-frac-exchange/data/CQ Frac Schedule 081919.xlsx: '2019-08-23T18:15:35.476604'
  /repositories/permian-frac-exchange/data/DE3_Frac_Schedule_8-21-2019.xlsx: '2019-08-23T18:15:47.430579'
  /repositories/permian-frac-exchange/data/Diamondback_3MonthFracSchedule_8.19.19_Midland.xlsx: '2019-08-23T18:15:41.416352'
  /repositories/permian-frac-exchange/data/Discovery NR 3 Month Frac Schedule 08-19-2019.xlsx: '2019-08-23T18:15:12.569296'
  /repositories/permian-frac-exchange/data/EER_FracSchedule_2019-08-19.xlsx: '2019-08-23T18:15:25.418005'
  /repositories/permian-frac-exchange/data/Earthstone Operating- Frac Schedule (FSEC).xlsx: '2019-08-23T18:15:34.397122'
  /repositories/permian-frac-exchange/data/Encana completions_081919.xlsx: '2019-08-23T18:15:08.812870'
  /repositories/permian-frac-exchange/data/Guidon Energy Frac_Schedule_20190821.xlsx: '2019-08-23T18:15:02.437182'
  /repositories/permian-frac-exchange/data/HeadingtonEnergy_19August19.xlsx: '2019-08-23T18:15:05.275727'
  /repositories/permian-frac-exchange/data/HenryResources_3MonthFracSchedule_20Aug2019.xlsx: '2019-08-23T18:15:27.926988'
  /repositories/permian-frac-exchange/data/HuntOil_3MonthFracSchedule_20Aug19.xlsx: '2019-08-23T18:15:21.372277'
  /repositories/permian-frac-exchange/data/IRM_3MonthFracSchedule_20190819.xlsx: '2019-08-23T18:15:26.444716'
  /repositories/permian-frac-exchange/data/LPI_3MonthFracSchedule_08192019.xls: '2019-08-23T18:15:19.984642'
  /repositories/permian-frac-exchange/data/Lario3MoFracSched_8_19_2019.xlsx: '2019-08-23T18:15:32.729337'
  /repositories/permian-frac-exchange/data/PB_Chevron_Frac Schedule 08-22-2019.xlsx: '2019-08-23T18:15:10.073985'
  /repositories/permian-frac-exchange/data/PE Frac Schedule_08.21.19.xlsx: '2019-08-23T18:15:01.183393'
  /repositories/permian-frac-exchange/data/Pioneer_FracSchedule_20190819.xlsx: '2019-08-23T18:15:16.327677'
  /repositories/permian-frac-exchange/data/SMENERGY_FracSchedule_22AUG2019.xlsx: '2019-08-23T18:15:07.349911'
  /repositories/permian-frac-exchange/data/SabaloOperating_3MonthFracSchedule_2019Aug19.xlsx: '2019-08-23T18:15:13.827501'
  /repositories/permian-frac-exchange/data/XTO_3MonthFracSchedule_ 8-21-19.xlsx: '2019-08-23T18:15:44.115745'
  test1: '2019-08-23T19:43:44.415657'
test1: test1
